C
C	OPEN ATOMIC COORDINATE FILE LUN=1
C	OPEN ESP OUTPUT FILE LUN=2/INPUT CHARGES, MAX SA BORN RADII
C
      SUBROUTINE FILOPN(INPT,IOUT,PCOD)
      IMPLICIT REAL*8 (A-H,O-Z)
      CHARACTER FILNAM*120,FILNAM2*120,FILNAM3*120,PCOD*(*),OUTPUT*120
      INTEGER RLEN
    1 WRITE (IOUT,'(A)') '$ENTER INPUT FILE NAME: '
      READ (INPT,'(A)') FILNAM
      WRITE (IOUT,*) ' filename = ',FILNAM
      OPEN (1,FILE=FILNAM,STATUS='OLD',IOSTAT=IERR)
      IF (IERR.NE.0) GO TO 990
      IP=1
      ILEN=RLEN(FILNAM)
      DO I=1,ILEN
      IF (FILNAM(I:I).EQ.'/') IP=I+1
      ENDDO
      PCOD=FILNAM(IP:IP+3)
      WRITE (IOUT,*) ' FILE NAME FOR DATA STRUCTURES'
      READ (INPT,'(A)') FILNAM2
      WRITE (IOUT,*) ' filename = ',FILNAM2
      OPEN(2,FILE=FILNAM2,STATUS='OLD',IOSTAT=IERR)
      IF (IERR.NE.0) GO TO 990
      WRITE (IOUT,*) ' FILE NAME FOR SOLVENT ENVIRONMENT'
      READ (INPT,'(A)') FILNAM3
      WRITE (IOUT,*) ' filename = ',FILNAM3
      OPEN(3,FILE=FILNAM3,STATUS='OLD',IOSTAT=IERR)
      IF (IERR.NE.0) GO TO 990
      WRITE(IOUT,*)'OUTPUT FILENAME'
      READ (INPT,'(A)') OUTPUT
      WRITE (IOUT,*) ' filname = ',OUTPUT
      OPEN(30,FILE=OUTPUT,
     *  STATUS='UNKNOWN',ACCESS='SEQUENTIAL',IOSTAT=IERR)
      IF (IERR.NE.0) GO TO 990
      RETURN
  990 IF (IERR.EQ.29) THEN
      WRITE (IOUT,*) ' FILE NOT FOUND'
      else
      WRITE (IOUT,*) ' error on open, ierr =',ierr
      WRITE (IOUT,1000) IERR
 1000 FORMAT(' I/O ERROR ON OPEN, STATUS = ',I5)
      CALL EXIT
      ENDIF
      END
